### ISSUE TITLE
Clean Velocity Installation Dropping Bunch of Errors

### ISSUE THREAD

**Issue by GronyRalph** [Elytrium/LimboAPI#105]
I literally just setup Velocity, haven't touched much, briefly followed this guide: https://github.com/Syrent/Switch-to-Velocity and installed LimboFilter along with API but it returns this in the console, I don't get any other errors.
https://paste.gg/p/anonymous/6b0b7a4ff0424c53b6f97d8a4167cd84
I'm using latest Velocity, it automatically downloaded, it has 512 MB RAM but it's a dynamic link so when reached the top, the virtual machine allows for more, Java 17.

**Comment by JNNGL** [comment]
sudo apt install fontconfig

**Comment by GronyRalph** [comment]
> sudo apt install fontconfig

Thank you
