### ISSUE TITLE
Maven server down?

### ISSUE THREAD

**Issue by kit8379** [Elytrium/LimboAPI#107]
**Describe the bug**
Maven server down?
**To Reproduce**
1. Visit https://https://maven.elytrium.net/repo/
2. No response

**Expected behavior**
It should be accessible.

**Additional context**
It made me can't use the API to code my plugin.

**Comment by kit8379** [comment]
> https://maven.jnngl.me/#/public

Thx

**Comment by JNNGL** [comment]
```xml
<repository>
  <id>repo</id>
  <name>Maven Repository</name>
  <url>https://maven.jnngl.me/public</url>
</repository>
```
