### ISSUE TITLE
[ENHANCEMENT] 1.20.2 Support

### ISSUE THREAD

**Issue by frafol** [Elytrium/LimboAPI#109]
**Describe the feature you'd like to have implemented**
Velocity 1.20.2 Support has been released, this plugin seems not compatible with it.

**Comment by RalphORama** [comment]
I'm still getting this warning in console: 

```
[limboapi]: Current LimboAPI version doesn't support current Velocity version (protocol version numbers: supported - 763, velocity - 764)
```

I'm on Velocity 3.2.0-SNAPSHOT (`git-2bd2c692-b269`)

**Comment by DHCPCD9** [comment]
> It looks like 1.20.2 support isn't fully working. With LimboAPI installed, I time out when trying to connect to my server.
> 
> I'm still getting this warning in console:
> 
> ```
> [limboapi]: Current LimboAPI version doesn't support current Velocity version (protocol version numbers: supported - 763, velocity - 764)
> ```
> 
> I'm on Velocity 3.2.0-SNAPSHOT (`git-2bd2c692-b269`)

https://github.com/Elytrium/LimboAPI/issues/109#issuecomment-1755990417

**Comment by RalphORama** [comment]
> [#109 (comment)](https://github.com/Elytrium/LimboAPI/issues/109#issuecomment-1755990417)

Sorry, misunderstood your post. Thought you meant the LimboAPI update had just released.

**Comment by H4kt** [comment]
Any ETA on the update?

**Comment by DHCPCD9** [comment]
> Any ETA on the update?

No ETA. Protocol has quetly changed, so it would be hard to implement 1.20.2 support.

**Comment by KweezyCode** [comment]
CONFIG STATE was added in 1.20.2 protocol, and as i see is is not implemented in LimboAPI (LoginListener.java file)

**Comment by UserNugget** [comment]
1.20.2 support was added long time ago, but looks like this issue was not closed for some reason.
