### ISSUE TITLE
[QUESTION] How to SpawnPlayer in 1.20.2?

### ISSUE THREAD

**Issue by f1den** [Elytrium/LimboAPI#118]
SpawnPlayer logic was removed and replaced by SpawnEntity :(

1.20.2 - https://wiki.vg/Protocol#Spawn_Entity

1.20.1 - https://wiki.vg/index.php?title=Protocol&oldid=18375#Spawn_Player

P.S. 
how can i fix limboHub?
i fixed all packet ids, but i can't change player logic with all versions support easily :(

make pull request if u know how.
(forked) https://github.com/f1den/LimboHub/

**Comment by kostya-main** [comment]
I tried your port and it turned out that when opening the menu on version 1.20.2 an error appears:
`Client disconnected with reason: Internal Exception: io.netty.handler.codec.DecoderException: net.minecraft.class_148: Loading NBT data`
Can you fix this or is it not on LimboHub side?

**Comment by an1by** [comment]
Same error.
![image](https://github.com/Elytrium/LimboAPI/assets/61041788/467e16a4-897e-44ef-a75f-5d2182df1c7a)
Problem in player logic in LimboAPI. LimboHub in other case works fine.
![image](https://github.com/Elytrium/LimboAPI/assets/61041788/54c5f0a0-df73-47e3-b4b8-0dae30e1715f)

**Comment by masmc05** [comment]
> I tried your port and it turned out that when opening the menu on version 1.20.2 an error appears: `Client disconnected with reason: Internal Exception: io.netty.handler.codec.DecoderException: net.minecraft.class_148: Loading NBT data` Can you fix this or is it not on LimboHub side?

it's on limbo api side, they didn't update the chunk serialization format to the 1.20.2 so when it reaches the nbt deserialization it's a mess instead of actual data, didn't update lots of packets ids to 1.20.2 etc

Limbo api still doesn't support 1.20.2 properly and that the cause of all that

**Comment by mdxd44** [comment]
i assume this one was fixed
