### ISSUE TITLE
[BUG] Protocol errors for clients after 1.20.1

### ISSUE THREAD

**Issue by DHCPCD9** [Elytrium/LimboAPI#129]
**Describe the bug**
Protocol errors after for all client versions after 1.20.1

**To Reproduce**
1. Enable premium on your account (or find another way to enfore online mode for users)
2. Log in with version 1.20.2 and later

**Expected behavior**
Login will be successful

**Screenshots**
![image](https://github.com/Elytrium/LimboAPI/assets/92095401/9050c344-c4fc-46d7-a20d-9358f43a4354)

**Comment by DHCPCD9** [comment]
[logs.txt](https://github.com/Elytrium/LimboAPI/files/13798467/message.3.txt)

**Comment by DHCPCD9** [comment]
[logs.txt](https://github.com/Elytrium/LimboAPI/files/13798468/message.3.txt)

**Comment by mqsl** [comment]
така сама проблема
same problem

**Comment by UserNugget** [comment]
You can workaround it via https://github.com/Elytrium/LimboAuth/issues/134#issuecomment-1869498706.
https://github.com/Elytrium/LimboAPI/pull/128 fixes this, but didn't tested completly yet
