### ISSUE TITLE
[BUG] Console Error Velocity 3.0

### ISSUE THREAD

**Issue by LucidAPs** [Elytrium/LimboAPI#130]
https://mclo.gs/v7PkMQg

**Comment by DHCPCD9** [comment]
Hello!

Thanks you for creating this issue, but unfortunately this details is not enogh to resolve issue.
Consider adding additional infomration, such as:
 - Velocity dump plugin (`velocity dump` in console)
 - Config of your plugin (You can remove data such as authorization tokens, IPs, etc.)
 - More detailed log
or try to do following actions, that can resolve your issue:
 - Update velocity to latest stable relese
 - Make sure that you using stable build of plugins
 - Ensure that you don't have installed plugins that conflicts with limbo(viaversion, and other)

**Comment by ilyaSeven7** [comment]
trying remove packetevents plugin 
your prb will solved 🤔

**Comment by mdxd44** [comment]
reopen issue with more details provided
