### ISSUE TITLE
[BUG] Exception on client 1.20.4 when denying login on LoginEvent

### ISSUE THREAD

**Issue by EpicPlayerA10** [Elytrium/LimboAPI#134]
**Describe the bug**
I have a velocity plugin that kicks player on `LoginEvent`. Here is an example:
```java
@Subscribe
public void onLogin(LoginEvent event) {
    event.setResult(LoginEvent.ComponentResult.denied(Component.text("test test")));
}
```

When I try to join to the proxy, then it shows this exception instead of the `test test` kick message:
![image](https://github.com/Elytrium/LimboAPI/assets/62206933/9071c4c5-801b-4010-9128-1c69f6a5f26b)

Without LimboAPI, the exception disappears.

**To Reproduce**
1. Setup a plugin with the event listener above.
2. Join to the proxy
3. See the exception in the kick message.

**Expected behavior**
It should show the `test test` kick message.

**Screenshots**
Attached above

**Server Info (please complete the following information):**
 - All Limbo plugins versions:
 - LimboAPI Release 1.1.18 Hotfix 2, downloaded from https://github.com/Elytrium/LimboAPI/releases/download/1.1.18/limboapi-1.1.18.jar

 - /velocity dump link [velocity-dump-2024-01-12-15-57-24.json](https://github.com/Elytrium/LimboAPI/files/13920500/velocity-dump-2024-01-12-15-57-24.json)

**Additional context**

**Comment by hevav** [comment]
fixed in https://github.com/Elytrium/LimboAPI/pull/128/commits/36bc4d6645dff07f17594579a59068cdde27114a
will be merged soon
