### ISSUE TITLE
[BUG]  Couldn't pass ProxyInitializeEvent to limboauth

### ISSUE THREAD

**Issue by serega404** [Elytrium/LimboAPI#139]
**Describe the bug**
When using any Velocity configuration (even a clean one) and installing the latest versions of LimboAPI and LimboAuth, an error appears in the console. This error does not interfere with authorization, and the server is working correctly, but the presence of this error is annoying

Error: `Couldn't pass ProxyInitializeEvent to limboauth
java.lang.NoClassDefFoundError: com/velocitypowered/proxy/protocol/packet/ServerLogin
`

[Full log](https://gist.github.com/serega404/ff80b2450ac05cb429f69d935642a376)

**To Reproduce**
1. Instal LimboAPI 1.1.20
2. Instal LimboAuth 1.1.13
3. See error

**Expected behavior**
The error does not appear

**Server Info:**
 - limboapi-1.1.20
 - limboauth-1.1.13.jar
 - velocity-3.3.0-SNAPSHOT, tested on 310, 329, 343
 - velocity [dump link](https://gist.github.com/serega404/afefdc1d55747f1f9ca8e44c131f0eb0)

**Comment by SkyWatcher2019** [comment]
Wrong repository, also problem is known

**Comment by serega404** [comment]
> Wrong repository, also problem is known

Sorry about the repository, I had several tabs open with both repositories

**Comment by serega404** [comment]
> Wrong repository, also problem is known

Now I found this error in another repository, but I couldn't do it before because the author uploaded the error as a photo
