### ISSUE TITLE
[BUG] build failure

### ISSUE THREAD

**Issue by Perets2207** [Elytrium/LimboAPI#144]
/home/runner/work/LimboAPI/LimboAPI/plugin/src/main/java/net/elytrium/limboapi/server/LimboSessionHandlerImpl.java:161: error: StartUpdatePacket() has private access in StartUpdatePacket

> Task :plugin:compileJava
        this.player.getConnection().write(new StartUpdatePacket());
                                          ^
/home/runner/work/LimboAPI/LimboAPI/plugin/src/main/java/net/elytrium/limboapi/server/LimboSessionHandlerImpl.java:165: error: StartUpdatePacket() has private access in StartUpdatePacket
      this.player.getConnection().write(new StartUpdatePacket());
                                        ^
/home/runner/work/LimboAPI/LimboAPI/plugin/src/main/java/net/elytrium/limboapi/server/LimboImpl.java:221: error: StartUpdatePacket() has private access in StartUpdatePacket
        .prepare(new StartUpdatePacket(), ProtocolVersion.MINECRAFT_1_20_2)
                 ^
/home/runner/work/LimboAPI/LimboAPI/plugin/src/main/java/net/elytrium/limboapi/server/LimboImpl.java:229: error: FinishedUpdatePacket() has private access in FinishedUpdatePacket
    this.configPackets.prepare(new FinishedUpdatePacket(), ProtocolVersion.MINECRAFT_1_20_2);
                               ^

**Comment by DHCPCD9** [comment]
Consider updating everything
