### ISSUE TITLE
No 1.16.5 version listed in the config

### ISSUE THREAD

**Issue by pref6** [Elytrium/LimboAPI#158]
**Describe the feature you would like to implement**.
    I would like to see support for limboapi version 1.16.5(this version is not listed).

**Is your feature request related to an existing problem? Please describe it**.
    My server core has version 1.16.5, the same is the minimum version to play on my server. LimboApi has 1.16.4 and then immediately 1.17. I have to use ViaBackward to close this small hole and downgrade the version to 1.16, as some players could log in with 1.16.4 and get an error from the server.

**Comment by hevav** [comment]
there's no difference between 1.16.4 and 1.16.5 protocol stuff
