### ISSUE TITLE
[BUG] Can't create plugin limboapi

### ISSUE THREAD

**Issue by cgw2023** [Elytrium/LimboAPI#166]
**Describe the bug**
A clear and concise description of the bug.

**To Reproduce**
1. start velocity

**Expected behavior**
plugin can run

**Screenshots**
no

**Server Info (please complete the following information):**
 - All Limbo plugins versions:
 - [e.g. LimboAPI 1.0.4-SNAPSHOT, downloaded from https://github.com/Elytrium/LimboAPI/actions/runs/xxxxxx]
 - [e.g. LimboFilter 1.0.3-rc3, downloaded from https://github.com/Elytrium/LimboAPI/actions/runs/xxxxxx]
limboapi 1.1.26
limbo reconnect 1.1.5
 - /velocity dump link [e.g. https://dump.velocitypowered.com/abcdef.json]
 
https://paste.denizenscript.com/View/127428

**Additional context**
https://mclo.gs/XeF1rtM

**Comment by SkyWatcher2019** [comment]
Update all limbo plugins

**Comment by UserNugget** [comment]
@cgw2023, can you try to reproduce this issue with the [latest dev-build](https://modrinth.com/plugin/limboapi/version/e632cff)?

**Comment by cgw2023** [comment]
is working, thank you so much
