### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by int3iku** [Elytrium/LimboAPI#168]
![image](https://github.com/user-attachments/assets/3ff8678d-b25f-40dd-87ed-a45d7ea53929)

![image](https://github.com/user-attachments/assets/fc3b0fbc-eb51-416f-a2ad-8adb6d92c907)

I use all the latest versions, and if I install liboapi, it does not work when working with packageevents!!

**Comment by mdxd44** [comment]
probably was fixed in 1858deabe433b4b42aacf079865eb9c2b73f0f58, please reopen the issue if wasn't
