### ISSUE TITLE
[BUG] LimboReconnect не возвращает игрока, когда основной сервер успешно перезагрузился

### ISSUE THREAD

**Issue by TheFaik** [Elytrium/LimboAPI#170]
**Describe the bug**
Плагин LimboReconnect не работает должным образом.
После перезапуска основного сервера, я всё равно остаюсь в велосити.
Можете посмотреть видео.

**To Reproduce**
1. Устанавливаете плагин LimboReconnect с LimboAPI 
2. Запускайте сервер велосити и основной сервер
3. Заходите в игру и выключаете основной сервер
4. Вы остаётесь на сервере велосити, но после перезагрузки основного сервера, вы всё также остаётесь на велосити, хотя вас должно перекинуть на основной сервер, как только

**Expected behavior**

**Screenshots**
Тут и без этого понятно, но на всякий, оставлю ссылку на видео:
https://www.youtube.com/watch?v=eUencrW1mWI

**Server Info (please complete the following information):**
 - All Limbo plugins versions:
 - LimboAPI (https://github.com/Elytrium/LimboAPI/actions/runs/11962360159)
 - LimboReconnect (https://github.com/Elytrium/LimboReconnect/releases/tag/dev-build)

https://pastebin.com/kBZwtryx

**Additional context**

**Comment by SkyWatcher2019** [comment]
1. Wrong repository
2. Your backend server is misconfigured so Velocity can't ping it. You can check it by enabling `debug` option in LimboReconnect config.
