### ISSUE TITLE
[BUG] clientbound/minecraft:block_entity_data

### ISSUE THREAD

**Issue by P3rsonal1ty** [Elytrium/LimboAPI#171]
![image](https://github.com/user-attachments/assets/154a1c1d-1dbf-4b1c-87c3-02b00d7b1f80)

![image](https://github.com/user-attachments/assets/27356b2a-70bf-4457-8539-299b86a56c2c)

when I connect to limbo, I get this bug 
![image](https://github.com/user-attachments/assets/0dcb803e-b58c-43c9-a345-62c97e6e7b3e)

limboapi-1.1.26/1.1.27.
Velocity 3.4.0
Minecraft: 1.21.1

**Comment by Bradlu378** [comment]
@P3rsonal1ty how you fixed that?
