### ISSUE TITLE
[BUG] When you install the latest versions of limboapi, limbofiler and limboauth, then version 1.21 simply does not launch the game

### ISSUE THREAD

**Issue by koterax** [Elytrium/LimboAPI#175]
**Describe the bug**
A clear and concise description of the bug.

**To Reproduce**
1. Set '...' in config to '...'
2. Do in game '....'
3. See error

**Expected behavior**

**Screenshots**

**Server Info (please complete the following information):**
 - All Limbo plugins versions:
 - [e.g. LimboAPI 1.0.4-SNAPSHOT, downloaded from https://github.com/Elytrium/LimboAPI/actions/runs/xxxxxx]
 - [e.g. LimboFilter 1.0.3-rc3, downloaded from https://github.com/Elytrium/LimboAPI/actions/runs/xxxxxx]

 - /velocity dump link [e.g. https://dump.velocitypowered.com/abcdef.json]

**Additional context**

**Comment by mdxd44** [comment]
The latest version of Velocity is currently not supported; use build 452
