### ISSUE TITLE
[BUG] Error limbofilter

### ISSUE THREAD

**Issue by Watghi** [Elytrium/LimboAPI#23]
**Describe the bug**
Limbofilter does not work.

**To Reproduce**
1. Install java 17, last velocity
2. Start server
3. And an error came out at startup

**Expected behavior**
What will LimboFilter work for

**Screenshots**
![2021-12-01_14 25 28](https://user-images.githubusercontent.com/95087767/144171670-1aa34f67-0629-4cdf-b666-6fb1974b03b3.png)

**Server Info (please complete the following information):**
 - LimboAPI Version [e.g. 1.0.2-SHAPSHOT, downloaded from https://github.com/Elytrium/LimboAPI/actions/runs/1520784680]
 - /velocity dump link [e.g. https://dump.velocitypowered.com/rezuzabara.json]

**Additional context**
- Server log link [https://pastebin.com/3291gDtN]

**Comment by mdxd44** [comment]
which version of minecraft?

**Comment by Watghi** [comment]
1.17.1

**Comment by hevav** [comment]
You are using Velocity version, which supports Minecraft 1.18, and this error means, that LimboAPI can't find packet definitions and mappings for the new Minecraft version. 
We'll add support of Minecraft 1.18 soon.
Temporarily use that Velocity build: https://ci.velocitypowered.com/job/velocity-3.0.0/91/
