### ISSUE TITLE
Plugin yml

### ISSUE THREAD

**Issue by lynrayy** [Elytrium/LimboAPI#25]
Could not load plugin from file plugins\limboauth-1.0.1-jdk11.jar
java.lang.NullPointerException: Plugin must have a plugin.yml or bungee.yml

**Comment by Watghi** [comment]
LimboApi plugin on Velocity, use Velocity [link: https://ci.velocitypowered.com/job/velocity-3.0.0/91/artifact/proxy/build/libs/velocity-proxy-3.1.0-SNAPSHOT-all.jar]

**Comment by mdxd44** [comment]
> Could not load plugin from file plugins\limboauth-1.0.1-jdk11.jar java.lang.NullPointerException: Plugin must have a plugin.yml or bungee.yml

Only velocity supported!
https://velocitypowered.com/
