### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by kanagawawave** [Elytrium/LimboAPI#3]
Thanks for this amazing plugin, its been a long wait for something like this for velocity and it works very well!!!

I have some suggestions idk if this is possible but i saw something like this here: https://github.com/XXMA16/BlitzLogin

Can you please add to allow cracked players with premium nicknames to join (second attempt or maybe a config like: attempts-before-cracked: 3)
Something like: retry-cracked-nickname: true/false

So if this is possible may an account is permanently locked in the first sucessfull state.
Ex: If the first sucessful login is an premium account they will only join with premium atempts
If a cracked player join with premium nickname they will be forever forced to execute /login to join

Its like saving the first sucessfull login on database for each account? Sorry i'm not the coding guy i'am just trying to figure all possible scenarios
And /unregister <nickname> is for reseting this "first state" or deleting from db

Sorry for my english.

**Comment by hevav** [comment]
Now you can use the "save-uuid" parameter in the config.yml of LimboAuth
