### ISSUE TITLE
[BUG] There is still a bug like in #29, an approximate solution to this problem will be described below

### ISSUE THREAD

**Issue by Watghi** [Elytrium/LimboAPI#31]
![image](https://user-images.githubusercontent.com/95087767/145263689-811d05d3-1135-4b1e-bd9d-b8f383cbb7e9.png)

Maybe fixed this way:
This can be solved in this way, a separate parameter is created in the database, let's say online-mode, if a player registers via offline-mode, then it is written to the online-mode parameter false, while this means that he can enter with a license, without a license, etc. If a player logs in with a license, then his parameter is written true, that is, online-mode true, and therefore he can only log in with a license.

Sorry my english, so bad

**Comment by hevav** [comment]
It's already fixed in the [5798ce7](https://github.com/Elytrium/LimboAPI/commit/5798ce733107643e81aeae38f719360899f064e4) commit, isn't it?

**Comment by Watghi** [comment]
> It's already fixed in the [5798ce7](https://github.com/Elytrium/LimboAPI/commit/5798ce733107643e81aeae38f719360899f064e4) commit, isn't it?

No

**Comment by Watghi** [comment]
Everything is working smoothly

**Comment by hevav** [comment]
What's wrong then, can you describe the situation?
Expected behavior, Steps to reproduce, etc...

**Comment by Watghi** [comment]
> What's wrong then, can you describe the situation? Expected behavior, Steps to reproduce, etc...

I logged in with offline-mode, registered using /reg 1234567890p 1234567890p, then turned off the server and turned on Online-mode-need-auth: false, and then logged in as a Second player with the same nickname, but with a license, and I was missed without entering a password, I don't know exactly how to explain.

**Comment by hevav** [comment]
This is fixed in the commit I referenced...

**Comment by Watghi** [comment]
> This is fixed in the commit I referenced...

wait, 10-20min

**Comment by Watghi** [comment]
Config before registration
![image](https://user-images.githubusercontent.com/95087767/145270659-ba3acedb-97d7-446a-8335-9c8e18d73c17.png)
Config after shutting down the server, and turning it on
![image](https://user-images.githubusercontent.com/95087767/145270753-f5f3f109-65bf-4b8c-8255-87599a181944.png)


Video:

https://drive.google.com/file/d/1_7XCD6dtkTNIjYiO62Truklpv00Z1Ad8/view?usp=sharing

**Comment by hevav** [comment]
Oh, okay, I get it. I'll fix it tomorrow

**Comment by Watghi** [comment]
> Oh, okay, I get it. I'll fix it tomorrow

Sorry for not understanding, I should have recorded the video right away

**Comment by mdxd44** [comment]
Closed in [cc2ccfb](https://github.com/Elytrium/LimboAuth/commit/cc2ccfbe22044e98a66257488cf5bd26e21ca340)
