### ISSUE TITLE
[BUG] A wall of text with errors

### ISSUE THREAD

**Issue by Gracv** [Elytrium/LimboAPI#32]
**Describe the bug**
A wall of text with errors.
https://mclo.gs/HqlE6hy

**To Reproduce**
1. Add limbo: api, auth and filter
2. Change nothing in the config
3. See error

**Expected behavior**
No errors

**Server Info (please complete the following information):**
 - LimboAPI Version [1.0.2, downloaded from https://github.com/Elytrium/LimboAPI/releases]
 - /velocity dump link [https://dump.velocitypowered.com/ugeziqoqup.json]

**Additional context**
BTW discord link is not working

**Comment by hevav** [comment]
Just ignore them, this is not a real error 
BTW it's fixed in dev builds
