### ISSUE TITLE
[BUG] H2 Database errors on startup

### ISSUE THREAD

**Issue by VictorGamer15** [Elytrium/LimboAPI#35]
**Describe the bug**
When Velocity 3.1.1 starts, LimboAuth 1.0.2 shows some errors in the console

**To Reproduce**
1. Make the database type "h2"
2. Start proxy
3. A large error appears

**Expected behavior**
I was expecting the plugin to not have any errors in console

**Screenshots**
![image](https://user-images.githubusercontent.com/69861104/147294916-8c2d9240-5dde-4116-b652-c15e4843507a.png)

**Server Info (please complete the following information):**
 - LimboAPI 1.0.2 [https://github.com/Elytrium/LimboAPI/actions/runs/1532157765]
 - https://dump.velocitypowered.com/erejopopak.json (Pastebin: https://pastebin.com/4QjX4xZ3)

**Additional context**
I'm using these plugins along SkinsRestorer

**Comment by mdxd44** [comment]
This already has been fixed in new builds from actions.
