### ISSUE TITLE
[BUG] Timed out

### ISSUE THREAD

**Issue by xaanndeer** [Elytrium/LimboAPI#37]
**Describe the bug**
Players time out when too long in limbo

**To Reproduce**
1. Make players join limbo with LoginLimboRegisterEvent
2. Wait for +- 30 seconds
3. You get timed out

**Expected behavior**
Players can stay in limbo as long as needed

**Screenshots**

**Server Info (please complete the following information):**
 - LimboAPI Version [1.0.2, downloaded from https://github.com/Elytrium/LimboAPI/releases/download/1.0.2/limboapi-plugin-1.0.2-jdk16.jar]
 - /velocity dump link [[e.g. https://dump.velocitypowered.com/dotihadufu.json](https://dump.velocitypowered.com/hisipugiye.json)]

**Additional context**
I make players download a resourcepack during this process, once I receive a successful response I send them to the lobby

**Comment by mdxd44** [comment]
This is due to the fact that in 1.0.2 we didn't send a keepalive packet. In latest build from actions this already has been fixed. By standard you will be kicked after read-timeout in velocity.toml.
