### ISSUE TITLE
Skins problem

### ISSUE THREAD

**Issue by Macialowskyyy** [Elytrium/LimboAPI#39]
SkinsRestorer plugin skins not working. There are no bugs in the console. You cannot see your own skin, but you can see others. Help

**Comment by HappyPerson2** [comment]
Can confirm

Velocity 3.1.1 build 98
Limbo API 1.0.3

**Comment by hevav** [comment]
We know the reason why it happens. We'll fix it soon

**Comment by Macialowskyyy** [comment]
> We know the reason why it happens. We'll fix it soon

Ok, let me add that flying through gamemode 3 blocks doesn't work. How premium login is enabled.

**Comment by hevav** [comment]
> Ok, let me add that flying through gamemode 3 blocks doesn't work. How premium login is enabled.
Have you tried the latest build (that was made 25 minutes ago)?

**Comment by Macialowskyyy** [comment]
> Have you tried the latest build (that was made 25 minutes ago)?

I'm already checking

**Comment by HappyPerson2** [comment]
The latest build (1.0.4) does not fix the issue.

**Comment by hevav** [comment]
> The latest build (1.0.4) does not fix the issue.

Try again with this new build

**Comment by Macialowskyyy** [comment]
it is okay
