### ISSUE TITLE
[BUG] "An unexpected error occurred while executing the command"

### ISSUE THREAD

**Issue by arteffAA** [Elytrium/LimboAPI#40]
"An unexpected error occurred while executing the command"
this error appeared when entering the password, there is a last build
![image](https://user-images.githubusercontent.com/53447407/152993406-ea726c3e-5074-4b56-8ea5-e5dbbe9cd303.png)

**Comment by hevav** [comment]
Use the build from the Actions tab

**Comment by hevav** [comment]
Кстати, можешь писать на русском)

**Comment by arteffAA** [comment]
Хахах, замечательно

**Comment by mdxd44** [comment]
а ты limboauth то обновил?

**Comment by mdxd44** [comment]
спигот != дев билд

**Comment by mdxd44** [comment]
качай с https://github.com/Elytrium/LimboAPI/actions
