### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by Watghi** [Elytrium/LimboAPI#44]
After passing the bot filter knocks out such an error
![image](https://user-images.githubusercontent.com/95087767/156157616-1e6e1318-27fc-422f-83ac-db3306d00801.png)

**Comment by hevav** [comment]
Are you sure that it is a LimboAPI issue? Does this issue remain after removing of the plugin?

**Comment by NoJokeFNA** [comment]
No its surely from LimboAPI. If you just let 1.18.2 clients bypass captcha and drop-check checks it works just fine.

**Comment by hevav** [comment]
As I see on the screenshot, there is a "minecraft:infiniburn_nether", when the latest LimboAPI version uses "#minecraft:infiniburn_nether".

**Comment by NoJokeFNA** [comment]
Mhh idk, he maybe didn't update yet. Does it work for you with 1.18.2?

**Comment by hevav** [comment]
>Does it work for you with 1.18.2?

Yes, it works for me
![image](https://user-images.githubusercontent.com/14876058/156200012-a0f042cd-d286-4fa6-99a4-e2b2fea6d9e4.png)

**Comment by hevav** [comment]
Whoops, I got it
