### ISSUE TITLE
[BUG] 1.18.2 failed join

### ISSUE THREAD

**Issue by Watghi** [Elytrium/LimboAPI#45]
Long login(screenshot 1) to the authorization server after it gives an error(screenshot 2), default settings, latest versions of limboapi, limboauth, limbofilter

limboapi: https://github.com/Elytrium/LimboAPI/actions/runs/1917176194
limboauth: https://github.com/Elytrium/LimboAuth/actions/runs/1806267878
limbofilter: https://github.com/Elytrium/LimboFilter/actions/runs/1732908930

velocity: Velocity 3.1.2-SNAPSHOT (git-2fe50bed-b115)

java: 17.0.2 Eclipse Adoptium

configs: default

screenshot 1: 
![image](https://user-images.githubusercontent.com/95087767/156268343-faae6d1e-958a-49fc-991a-dae0a5e9350b.png)
screenshot 2: 
![image](https://user-images.githubusercontent.com/95087767/156268388-c4f4f211-1721-49ac-986a-c55e14bb6568.png)

**Comment by hevav** [comment]
I know, It is a LimboAuth bug. I'll fix it as soon as possible
