### ISSUE TITLE
[ENHANCEMENT] Forward Floodgate Data to Backend Servers

### ISSUE THREAD

**Issue by kuzuanpa** [Elytrium/LimboAPI#47]
**Describe the feature you'd like to have implemented**
Forward floodgateAPI data to backend servers

**Is your feature request related to an existing problem? Please describe.**
In this version,bedrock players can't use ALL function of floodgate,such as Account Linking and so on.
also,other plugins use floodgate API is broken.
The most serious problem is that I >can't use any AntiCheat plugin< because They can't determine which player is bedrock and see them all as java players ,so that bedrock player receives Lots of false positives making my players can't play normally

**Additional context**
![IMG_0984](https://user-images.githubusercontent.com/61902985/159004197-2610a036-1f2a-49fe-b79c-2b3f19ea8605.jpg)

**Comment by hevav** [comment]
We know about the Floodgate issue, we will fix if as soon as possible
