### ISSUE TITLE
[ENHANCEMENT]  1.18.2 Support

### ISSUE THREAD

**Issue by FLYEMOJ1** [Elytrium/LimboAPI#50]
**Describe the feature you'd like to have implemented**
Add 1.18.2 Support

**Is your feature request related to an existing problem? Please describe.**
Yes. Our server want use LimboAPI + LimboAuth + LimboFilter. But it cant be used.

**Additional context**
No. But I want it get supported ASAP.

**Comment by hevav** [comment]
Use dev build. It supports 1.18.2

**Comment by Gracv** [comment]
1.18.2 is supported. Use dev builds

**Comment by FLYEMOJ1** [comment]
Thanks for reply.
I will try it later.
