### ISSUE TITLE
[BUG] was kicked due to keepalive timeout.

### ISSUE THREAD

**Issue by 864063334** [Elytrium/LimboAPI#52]
**Describe the bug**
When I link to the server using the domain name, it prompts me"[19:22:50 WARN] [limboapi]: [connected player] Wagic_ (/113.116.171.135:2189) was kicked due to keepalive timeout."
When I enter with 127.0.0.1, I can access the server.
**To Reproduce**
Use the domain name, go to the server, kick out
[19:22:48 INFO] [limboapi]: Wagic_ (/113.116.171.135:2189) has connected to the LimboFilter Limbo
[19:22:48 INFO] [limbofilter]: [connected player] Wagic_ (/113.116.171.135:2189) has client brand fabric
[19:22:50 WARN] [limboapi]: [connected player] Wagic_ (/113.116.171.135:2189) was kicked due to keepalive timeout.
[19:22:50 INFO] [limboapi]: Wagic_ (/113.116.171.135:2189) has disconnected from the LimboFilter Limbo

**Server Info (please complete the following information):**
 - All Limbo plugins versions:
limboapi-plugin-1.0.4-SNAPSHOT
limboauth-1.0.4-SNAPSHOT
limbofilter-1.0.4-SNAPSHOT
 - /velocity dump link [e.g. [link](https://dump.velocitypowered.com/qiyebatana.json)

**Additional context**
[latest.log](https://github.com/Elytrium/LimboAPI/files/8602492/latest.log)

**Comment by hevav** [comment]
plugins/limbofilter/config.yml -> max-ping

**Comment by 864063334** [comment]
> plugins/limbofilter/config.yml -> max-ping

Its value is 2000 and when I change it to 20000 I can use the domain to access the server, what should its correct value be? Thank you very much!

**Comment by Xardion495** [comment]
Have the same case. Guess it is not depends on ip mask type, it's just all about the connection latency. I Increased a max-ping from 2000 to 5000 (5 sec). Works normally yet for now.
If your server deployed in 3-rd party country this parameter is better to change and test.
