### ISSUE TITLE
[ENHANCEMENT] GeyserMC Support

### ISSUE THREAD

**Issue by iamflorencejay** [Elytrium/LimboAPI#55]
**Describe the feature you'd like to have implemented**
I want to add Geyser to the Limbo API because it is on invalid ping packet territory. 

**Is your feature request related to an existing problem? Please describe.**
A clear and concise description of what the problem is.

**Additional context**
![Screenshot_2022-06-11-11-16-40-415_com mojang minecraftpe](https://user-images.githubusercontent.com/24932514/173170623-52cb31aa-d28d-4f80-ac74-599ba9a6b8b1.jpg)

**Comment by hevav** [comment]
Try to adjust the max-ping setting in LimboFilter config
