### ISSUE TITLE
[BUG] unusual problem in Velocity (1.19.2)

### ISSUE THREAD

**Issue by WieszczY85** [Elytrium/LimboAPI#60]
Hello,
I use last version dev for limboapi and limbofilter.
The server is 1.19.2 last version Velocity 3.1.2-SNAPSHOT (git-6496983c-b171)
Viaversion:
[https://github.com/ViaVersion/ViaVersion/issues/3084](https://github.com/ViaVersion/ViaVersion/issues/3084)
I have noticed something odd:
1. Problems with connecting players to the server ("time out")
First, I have incrased connection time in config to fix it, but it didn't work.
2. The moment player enters the server and takes damage from mob or another player, it kicks him out to the lobby. Proxy console gets multiple errors from Viaversion.
At first, I thought that the problem is caused by VIA so I reported the issue here:
[https://github.com/ViaVersion/ViaVersion/issues/3084](https://github.com/ViaVersion/ViaVersion/issues/3084)
Unfortunately it didn't help, even after removing the VIA. I went through all the files and figured out which plugins cause the problem.
Everything got back to normal after I removed LimboAPI and LimboFilter.

**Server Info (please complete the following information):**
 - All Limbo plugins versions:
 - LimboAPI 1.0.6-SNAPSHOT (git-9fbc8153), downloaded from https://github.com/Elytrium/LimboAPI/releases/tag/dev-build-jdk-17
 - LimboFilter 1.0.6-SNAPSHOT, downloaded from https://github.com/Elytrium/LimboFilter/releases/tag/dev-build-jdk-17
 - /velocity dump link [https://dump.velocitypowered.com/fohokayomo.json](https://dump.velocitypowered.com/fohokayomo.json)
  (without limbo plugin)
.

**Comment by AVuTuVA** [comment]
Delete viaversion from proxy and install on server
