### ISSUE TITLE
[BUG] Incompatibility with Raknetify

### ISSUE THREAD

**Issue by CamperSamu** [Elytrium/LimboAPI#61]
**Describe the bug**
When attempting to join a Velocity Proxy via Raknet using [RelativityMC/raknetify](https://github.com/RelativityMC/raknetify/) the client will crash or get stuck on the connection screen.
Apparently LimboAPI forces packet compression or mishandles packets in some way when working with Raknetify.
All the details are on https://github.com/RelativityMC/raknetify/issues/15

**To Reproduce**
1. Install Raknetify and LimboAPI + LimboAuth on a Velocity Proxy
2. Host a Paper or Fabric/Quilt server (with Raknetify if possible)
3. Attempt to join

**Expected behavior**
The client should join the server without issues.

**Screenshots**
_All the details are on https://github.com/RelativityMC/raknetify/issues/15, screenshots included._

**Server Info (please complete the following information):**
All Limbo plugins versions:
 - limboapi-plugin-1.0.6-SNAPSHOT-9fbc8153
 - limboauth-1.0.6-SNAPSHOT
 - LimboAuth.Social.Addon-1.0.2

 - https://dump.velocitypowered.com/newehebuxe.json

**Additional context**
I hope this can be sorted out since I'd like to give my players the option to use Raknetify and I really like the social addon since it allows my server to avoid being griefed to a hacked account.

**Comment by HyCore** [comment]
Please fix this, it would be very helpful <3

**Comment by TH2403y** [comment]
Please fix this

**Comment by dentatar** [comment]
Same issue here after a whole year

**Comment by ERroooooR** [comment]
Please fix this

**Comment by TH2403y** [comment]
Same issue here after a whole year!!!

**Comment by TH2403y** [comment]
Use NanoLimbo.

**Comment by HaHaWTH** [comment]
Still reproducible on latest LimboAPI (with save-uncompressed-packet enabled) and Velocity, hope this will be resolved, amazing devs🥺 <3

**Comment by mdxd44** [comment]
resolved in 6b3fb97a1e715bc4a0d3801399c1fae56eab895c
