### ISSUE TITLE
[meta] elytrium.net and ely.su are inaccessibile

### ISSUE THREAD

**Issue by CamperSamu** [Elytrium/LimboAPI#63]
I don't have a good way to contact you [Elytrium developers] directly since access to the website seems to be locked, so I am going to open a issue here.

Apparently the Elytrium website and ely.su short link appear to be inaccessibile due to the website returning an invalid SSL response (`ERR_SSL_PROTOCOL_ERROR` on Chromium browsers).

Because of this, outside of the website, services like the Discord server are inaccessible (and I believe the support e-mail is too).

Since I haven't seen too much activity on the project in the last 25 days or so and the website inaccessibility I got worried that something happened to the project.

I hope this is not the case, sorry for bothering.

**Comment by hevav** [comment]
We have a problem with our CDN provider, so our website is down right now.
E-mail works correctly.
You can use this link to join our discord server: https://discord.gg/sHkXM46nsN

**Comment by CamperSamu** [comment]
Thanks for the quick response, this issue will be closed once the website comes back online so if anyone is wondering can just look at this issue.

**Comment by hevav** [comment]
The website will be up within an hour
