### ISSUE TITLE
[meta/enhancement] Publish Limbo plugins on modrinth.com

### ISSUE THREAD

**Issue by CamperSamu** [Elytrium/LimboAPI#64]
**Describe the feature you'd like to have implemented**
[Modrinth](https://modrinth.com/) is a very cool and easy to work Minecraft modding site, way easier to use than Velocity Forums, far better than SpigotMC.
They recently added the ability to publish plugins and resource packs alongside mods, you might want to look into hosting downloads there too.
They have an API that allows automated releases and direct downloads, a maven mirror for the jars and much more.

**Is your feature request related to an existing problem? Please describe.**
The Velocity plugins community is too fragmented as the Velocity Forums suck for plugin visibility.

**Additional context**
https://modrinth.com/

**Comment by SkyWatcher2019** [comment]
+

**Comment by hevav** [comment]
![image](https://user-images.githubusercontent.com/14876058/207668137-d56bb8d3-a9e1-4995-9a6e-dd4ca45bf99d.png)
