### ISSUE TITLE
Why does PlayerListItemHook exist?

### ISSUE THREAD

**Issue by Osiris-Team** [Elytrium/LimboAPI#66]
I get uuid == null (or `java.lang.AssertionError: 1.7 tab list entry given to modern tab list handler!` with assertions enabled) when trying to forward a player from the limbo to another server.
I figured the cause for this issue may lie in PlayerListItemHook class line 58/60.
Why does that code even exist can't make sense of it?
The initialID seems to be null and causing the issue.
I removed that code and now It works... Still would like to know what it does and why it exists.

**Comment by hevav** [comment]
This is the only way to modify client uuid, since in LimboAPI, when logging in, player spawns before the GameProfileRequestEvent gets triggered.

**Comment by Osiris-Team** [comment]
Why do you need to modify the client uuid?

**Comment by Osiris-Team** [comment]
When trying to forward from limbo to another server it fails and my client receives this error message:
Disconnected: translation{key='disconnect.genericReason', args=[Internal Exception: io.netty.handler.codec.DecoderException: java.util.zip.DataFormatException: incorrect header check]}

Any ideas? There isnt anything in the proxy or mc server logs only that the client disconnected.

**Comment by Osiris-Team** [comment]
I think I found the error, was my mistake I guess.
Switched to nanolimbo however :/
