### ISSUE TITLE
[BUG] Limbo leave causes client exception

### ISSUE THREAD

**Issue by frafol** [Elytrium/LimboAPI#70]
**Describe the bug**
Limbo, when it has to send several players simultaneously to the same server, kicks out some clients (not all players are kicked out) due to a packet compression error.

**To Reproduce**
1. Trying to simultaneously connect several players connected to a limbo in a specific server.

**Screenshots**
https://i.imgur.com/VJC0Fw4.png
https://i.imgur.com/4JHG9FT.png

**Server Info (please complete the following information):**
 - [e.g. LimboAPI 1.0.6-SNAPSHOT, downloaded from https://github.com/Elytrium/LimboAPI/releases/download/1.0.6/limboapi-plugin-1.0.6-jdk17.jar]

**Comment by frafol** [comment]
also tried with latest dev build

**Comment by frafol** [comment]
The problem is not solved, same error by upgrading LimboAPI to version 1.0.8 (the new packets saving option is enabled).

**Comment by hevav** [comment]
@frafol do you use LimboPlayer#disconnect method to disconnect the player from Limbo and send to another server?

**Comment by mdxd44** [comment]
if this is still happens please reopen an issue
