### ISSUE TITLE
[BUG] Rare error when someone tries to join

### ISSUE THREAD

**Issue by Wilkovsky** [Elytrium/LimboAPI#72]
**Describe the bug**
When someone tried to join the server this error appeared in console. Everyone join without problems but this player generated error

**To Reproduce**
1. Try to join the server

**Expected behavior**
Fix this error

**Screenshots**
![image](https://user-images.githubusercontent.com/120938723/208300896-23771f9a-e368-4d3f-931d-ec354009f9a7.png)

**Server Info (please complete the following information):**
- LimboFilter 1.0.7, downloaded from https://github.com/Elytrium/LimboFilter/releases
- LimboAuth 1.0.7, downloaded from https://github.com/Elytrium/LimboAuth/releases
- LimboAPI 1.0.7, downloaded from https://github.com/Elytrium/LimboAPI/releases
all plugins for jdk17

 - /velocity dump link - https://dump.velocitypowered.com/qaxasuxava.json

**Comment by hevav** [comment]
Fixed in 1.0.8
