### ISSUE TITLE
[BUG] Не загружаются Limbo-плагины.

### ISSUE THREAD

**Issue by Nektoo** [Elytrium/LimboAPI#75]
Здравствуйте. Недавно столкнулся с проблемой, как мне сказали в поддержке **lifehosting** проблема в ядре и нужно обновить плагины. Ядро у меня стоит **velocity-3.2.0-SNAPSHOT-215.jar** https://papermc.io/downloads#Velocity (#216). 

Плагины не создают свои папки, вот логи:
[latest (1).log](https://github.com/Elytrium/LimboAPI/files/10332266/latest.1.log)

Мой дискорд: Nekto#1061 (490518336547848213)

**Comment by Nektoo** [comment]
И это ошибка не только у меня на хостинге. Они не загружаются и у других.

**Comment by Nektoo** [comment]
Плагины от Limbo:
> limbofilter-1.0.8-SNAPSHOT.jar
> limboapi-plugin-1.0.8-SNAPSHOT-4a46385c.jar
> limboauth-1.0.7-jdk17.jar

**Comment by hevav** [comment]
LimboAPI пока что не поддерживает Velocity 3.2.0
Либо откатись до версии 3.1.2, либо жди обновлений

**Comment by hevav** [comment]
Выпустили обновление, проверяй

**Comment by MikeTheEngenner** [comment]
Не работает LimboAPI 1.0.7JDK17, Velocity 3.2.0 snapshot 216 и 215 пробовал
![image](https://user-images.githubusercontent.com/73390095/210270918-f31272d0-824e-4ead-8c73-e6f65dab4985.png)
