### ISSUE TITLE
[BUG] Too many players are kicked due to keepalive timeout after 1 second of connection

### ISSUE THREAD

**Issue by osx11** [Elytrium/LimboAPI#77]
**Describe the bug**
As I've seen in the code, the keepalive timeout is 30 seconds, however, many players are kicked just after they connect to the server

**To Reproduce**
I did not found the way to reproduce. 100+ players do not have this problem, but every time I open console I see that about 10 players simultaneously can't connect to the server.

**Expected behavior**
No timeout after 1 second of connection.

**Screenshots**
https://i.imgur.com/YrR4zbo.png

**Server Info (please complete the following information):**
 - All Limbo plugins versions:
 - LimboAPI 1.0.8, downloaded from https://github.com/Elytrium/LimboAPI/releases/download/1.0.8/limboapi-plugin-1.0.8-jdk17.jar
 - LimboFilter 1.0.8, downloaded from https://github.com/Elytrium/LimboFilter/releases/download/1.0.8/limbofilter-1.0.8-jdk17.jar

 - [/velocity dump link](https://dump.velocitypowered.com/zogibigeqe.json)

**Comment by ImNotSoftik** [comment]
Same problem

**Comment by lgc2333** [comment]
same when using mcbe and geyser to connect to velocity

**Comment by pigeonov** [comment]
bump
