### ISSUE TITLE
[BUG] after enabling the `ping_passthrough` of geyser. bedrock player will kicked out for "%prefix Timed out" reason.

### ISSUE THREAD

**Issue by FallenCrystal** [Elytrium/LimboAPI#79]
**Describe the bug**
kick bedrock player.
**To Reproduce**
1. Enable LimboAPI & LimboFilter
2. Enable `ping_passthrought` in geyser config.
3. use bedrock client join the server.
4. got kicked.

**Expected behavior**
players will not be kicked out.

**Screenshots**
nope

**Server Info (please complete the following information):**
 - All Limbo plugins versions:
LimboAPI-Release1.1.7
LimboFilter-Release1.1.8
LimboAuth-Release1.1.11
LimboAuth Soical Addon-Release1.0.10

https://dump.velocitypowered.com/xileniwune.json

**Additional context**
nope

**Comment by Onako2** [comment]
I am also experiencing that behavior.

**Comment by mdxd44** [comment]
probably was fixed in 3952869
