### ISSUE TITLE
[FEATURES] Weak password, Session timer, Unregister [LimboAUTH]

### ISSUE THREAD

**Issue by TheKlimoT** [Elytrium/LimboAPI#8]
Add new command:

* /startsession - Start a session that does not require a password
* /destroysession - Delete a session that does not require a password
* /unregister password - Unregistered account

Reconstructed command 2fa:

It is much more convenient when there are 2 different commands.

* /2fa
* /disable2fa <key>

-----------------------
Add new functionality:

Make a check for the password that will be stored in the file password.txt so that players don't set weak passwords.

The system of returning the player to the server on which he was. Let's say the player was on the surv1 server - and the next time he visits, he will be immediately redirected to this server.

Add bossbar - the time before the expiration of authorization / registration, and the time output is seconds, as well as custom text.

Add functionality to messages if the quotes are empty, the message will not be sent to the player. Example: login-success: "" - and this message will not come to the player.

Add a Title system, let's say instead of chat messages, the Main-Title, Sub-Title will be displayed to the player

**Comment by hevav** [comment]
> /startsession - Start a session that does not require a password
> /disable2fa
This features look really strange 

> The system of returning the player to the server on which he was. Let's say the player was on the surv1 server - and the next time he visits, he will be immediately redirected to this server.
We believe that this feature is not intended for auth plugins.

> /destroysession - Delete a session that does not require a password
> /unregister password - Unregistered account
> Make a check for the password that will be stored in the file password.txt so that players don't set weak passwords.
> Add bossbar - the time before the expiration of authorization / registration, and the time output is seconds, as well as custom text.
> Add functionality to messages if the quotes are empty, the message will not be sent to the player. Example: login-success: "" - and this message will not come to the player.
> Add a Title system, let's say instead of chat messages, the Main-Title, Sub-Title will be displayed to the player
This features will be released today

**Comment by mdxd44** [comment]
Closed in [5fe79b9](https://github.com/Elytrium/LimboAuth/commit/5fe79b92327c082384068fa45c3b1d2691800e3d)
