### ISSUE TITLE
[BUG] Wrong ConnectedPlayer Phase after exiting Limbo (FML)

### ISSUE THREAD

**Issue by Twarug** [Elytrium/LimboAPI#81]
**Describe the bug**
After exiting from Libmbo, ConnectedPlayer (connection between proxy and modded player with Forge) has set `LegacyForgeHandshakeClientPhase.NOT_STARTED`, but it should be set to `LegacyForgeHandshakeClientPhase.COMPLETED`.
This is becouse of lack of Handshake reset, because Limbo sets `spawned` field in `ClientPlaySessionHandler`.
Because of this, player cannot switch between any, of the other servers connected to proxy.

**To Reproduce**
1. Connect to proxy
2. Try to switch to other server connected to the proxy

**Expected behavior**
Posibility of switching server

**Screenshots**

**Server Info (please complete the following information):**
 - Velocity 3.2.0-SNAPSHOT, downloaded from https://api.papermc.io/v2/projects/velocity/versions/3.2.0-SNAPSHOT/builds/226/downloads/velocity-3.2.0-SNAPSHOT-226.jar
 - LimboAPI 1.1.7-SNAPSHOT, downloaded from https://github.com/Elytrium/LimboAPI/releases/tag/1.1.7/
 - Client: Forge 1.12.2

**Additional context**
I tried to fix this problem, by debugging all incoming and outgoing packet, and thats all what i found. Unfortuanly I'm not capable of fixing it.

**Comment by hevav** [comment]
I'll take a look today/tomorrow.

**Comment by Kritex** [comment]
I am having same problem

**Comment by DEv0on** [comment]
@Kritex Look at our fork at [ReModded/LimboAPI](https://github.com/ReModded/LimboAPI). We made a quick fix for this and i think this is one of the best fixes possible without making a lot of changes. Velocity made same thing in their handling of FML_HS on non-forge servers.
[commit](https://github.com/ReModded/LimboAPI/commit/a1938ef7aa7783c957532b7f3314b2925cc72c40)
