### ISSUE TITLE
[BUG] Signed chat messages not working

### ISSUE THREAD

**Issue by D3it7i** [Elytrium/LimboAPI#87]
**Describe the bug**
Signed chat not working after installing limboapi

**To Reproduce**
1. install limbo API 1.1.12 Hotfix 1
2. Join the game with a premium account, then send a chat message
3. Signed chat could not be verified

**Expected behavior**
Chat signatures are verifiable when advanced players and UUIDs have not been modified(After removing limboapi, the chat verification is completely normal)

**Server Info (please complete the following information):**
 - All Limbo plugins versions:
 - limbo API 1.1.12 Hotfix 1, downloaded from https://github.com/Elytrium/LimboAPI/releases/tag/1.1.12
 - velocity dump link: https://cpaste.org/?780803f0c904d9ce#62nV1RzfYEUkkmjgk5niXiFMwXFhGzyycvVcJnGRKvDF

**Additional context**
According to my test, PlayerChatSessionPacket is not handled correctly, player.getIdentifiedKey() is always null
Causes PlayerChatSessionPacket to be discarded forever
https://github.com/Elytrium/LimboAPI/blob/91bedd5dad5e659092fbb0a7411bd00d67044d01/plugin/src/main/java/net/elytrium/limboapi/protocol/packets/c2s/PlayerChatSessionPacket.java#L54-L61
this.player.getIdentifiedKey() is always null
https://github.com/Elytrium/LimboAPI/blob/91bedd5dad5e659092fbb0a7411bd00d67044d01/plugin/src/main/java/net/elytrium/limboapi/injection/login/LoginTasksQueue.java#L207-L211
If the PlayerChatSessionPacket is no longer discarded, then the signed chat of the premium account can be verified (if the UUID is different, it will still be kicked out by the server)。

**Confirm in 1.1.13**

**Comment by D3it7i** [comment]
Confirm in 1.1.16

**Comment by Brickgard** [comment]
Seeing this behavior using Velocity 3.2.0 build #296 and LimboAPI 1.1.17 dev-build-1.20.2 
Servers and Client using 1.20.2.
Same behavior as original post, chat signatures functional until LimboAPI is present, only change is adding/removing LimboAPI to the Velocity proxy.

**Comment by EnchStudio** [comment]
i got same probelam，please fix @hevav

**Comment by D3it7i** [comment]
Confirm in 1.1.18

**Comment by manul694** [comment]
why do you need signed chat bro
