### ISSUE TITLE
[BUG] Limbo#registerCommand Not Working

### ISSUE THREAD

**Issue by TheoBong** [Elytrium/LimboAPI#90]
**Describe the bug**
The method Limbo#registerCommand does not work as intended. When I attempt to run the command '/leave' in the limbo, nothing happens. I am unable to run any velocity registered commands inside the limbo. Here is the code:

```
        Limbo limboServer = factory
                .createLimbo(authWorld)
                .setName("LimboAuth")
                .setWorldTime(1000L)
                .setGameMode(GameMode.ADVENTURE);

        commandManager.registerCommand(new LeaveCommand(limboServer, playerFinder, defaultServer));
        limboServer.registerCommand(
                new LimboCommandMeta(Arrays.asList("leave", "hub", "l", "lobby")));
```

**Expected behavior**
When I type '/leave' in the limbo, it should execute the code from that command.

**Server Info (please complete the following information):**
 - LimboAPI 1.1.13 (in pom file) & LimboAPI 1.1.12 (in plugins folder)
 - Velocity 3.1.2-SNAPSHOT
 - acf-velocity 0.5.1-SNAPSHOT

 - /velocity dump link -- attached below in txt format

[velocity-dump-2023-05-02-05-31-31.txt](https://github.com/Elytrium/LimboAPI/files/11370018/velocity-dump-2023-05-02-05-31-31.txt)

**Comment by hevav** [comment]
You should handle commands manually, overriding onChat(String) method of LimboSessionHandler. It's intended that Velocity-registered commands don't work inside Limbo

**Comment by TheoBong** [comment]
> You should handle commands manually, overriding onChat(String) method of LimboSessionHandler. It's intended that Velocity-registered commands don't work inside Limbo

What is the Limbo#registerCommand method intended to be used for then?

**Comment by hevav** [comment]
To register 1.13+ command meta on client (It enables tab completion on 1.13+ clients) 
Without executing this method, Forge 1.13+ will crash on every command entered by player

**Comment by hevav** [comment]
Limbo is designed as a lightweight server, so you should do a lot manually

**Comment by TheoBong** [comment]
I see, do you have an example of sorts of how I could execute existing velocity commands into onChat method?

**Comment by TheoBong** [comment]
Or do I just have to do that manually with some refactoring

**Comment by hevav** [comment]
I don't have any examples =(

**Comment by TheoBong** [comment]
Figured, I took a look at velocity code to see if I could somehow reuse their command-registration logic but it seems I'd have to abstract my commands to be runnable by both limbo and regular servers

**Comment by TheoBong** [comment]
For anyone else looking at this issue, if you're using aikar's command framework here's some code that works:

```
    @Override
    public void onChat(String message) {
        if (!message.startsWith("/")) return;

        String[] args = message.split(" ");
        String[] modifiedArgs = Arrays.copyOfRange(args, 1, args.length);

        for (RootCommand rootCommand : commandManager.getRegisteredRootCommands()){
            if (("/" + rootCommand.getCommandName()).equals(args[0])) {
                rootCommand.execute(commandManager.getCommandIssuer(proxyPlayer), args[0], modifiedArgs);
                return;
            }
        }
    }

```
