### ISSUE TITLE
[question] how to send player from limbo -> spigot server

### ISSUE THREAD

**Issue by TheoBong** [Elytrium/LimboAPI#91]
I feel dumb asking, but I can't seem to figure out how to send a player connected to the limbo onto a registered server. Here are the methods I've tried unsucessfully: `LimboFactory#passLoginLimbo`, `Limbo#dispose`, and `Player#createConnectionRequest`

**Comment by TheoBong** [comment]
Nevermind, I found the LimboPlayer#disconnect method.

**Comment by Black-HIG** [comment]
I meet the same problem, can you tell me how you solved this problem

**Comment by TheoBong** [comment]
> I meet the same problem, can you tell me how you solved this problem

I already stated when I closed this issue, are you not able to see it?

**Comment by Black-HIG** [comment]
> > I meet the same problem, can you tell me how you solved this problem
> 
> I already stated when I closed this issue, are you not able to see it?

Sorry, i saw
