### ISSUE TITLE
[BUG] I can't send player to other server

### ISSUE THREAD

**Issue by Black-HIG** [Elytrium/LimboAPI#97]
**Describe the bug**
When i use LimboPlayer#disconnect to send player to other server, there is only xxx disconnected from xxx limbo, but i am still in the limbo server

**To Reproduce**

**Expected behavior**
Send me to other server

**Screenshots**
None

**Server Info (please complete the following information):**
 -LimboAPI 1.1.14 download from github
- LimboSelect wrote by myself

 - [Velocity dump link](https://pastebin.com/Q2fUMDba)

**Additional context**
None

**Comment by JNNGL** [comment]
Should be fixed in [0d31466](https://github.com/Elytrium/LimboAPI/commit/0d31466afb4429c93a43c998f2461967bf654aa9)

**Comment by TheoBong** [comment]
I don’t appreciate you blanking comments on my issue. Please do your part by linking this issue on my issue and properly stating the resolution. This helps everyone to fix stuff faster. Deleting your comment after I tried to help is shameful.

**Comment by JNNGL** [comment]
> I don’t appreciate you blanking comments on my issue. Please do your part by linking this issue on my issue and properly stating the resolution. This helps everyone to fix stuff faster. Deleting your comment after I tried to help is shameful.

?

**Comment by TheoBong** [comment]
> > I don’t appreciate you blanking comments on my issue. Please do your part by linking this issue on my issue and properly stating the resolution. This helps everyone to fix stuff faster. Deleting your comment after I tried to help is shameful.
> 
> ?

Not you, the OP

**Comment by Black-HIG** [comment]
It kicked me with "Internal Exception: io.netty.handler.codec.DecoderException: java.util.zip.DataFormatException: incorrect header check"

**Comment by Black-HIG** [comment]
@JNNGL

**Comment by JSH32** [comment]
Im also getting this

**Comment by Owen1212055** [comment]
<img width="1901" alt="Screenshot 2023-07-30 at 3 38 36 PM" src="https://github.com/Elytrium/LimboAPI/assets/23108066/b1d1247d-9af6-48f7-8779-2895694d9f1d">
When using disconnect to forward the player to another server, I also see this issue.
